		<footer>
			<nav>
				<ul>
					<li><a href="/">Главная</a></li>
                                        <li><a href="/product/index">Каталог</a></li>
                                        <li><a href="/company/delivery">Доставка</a></li>
                                        <li><a href="/company/about">Контакты</a></li>
                                        <li><a href="/company/portfolio">О компании</a></li>
				</ul>	
			</nav>
			<div class="footer-bottom">
				<div class="contact">
					<p>&copy 2007-2011 Интернет-супермаркет «Elwau.ru»</p>
					<address> Адресс: 105118, г.Москва, ул. Кирпичная, д. 22</address>
					<p>Тел.: +7 (495) 540-55-11, 8 (800) 555-55-90</p>
					<p>Email: info@elwau.ru</p>
				</div>
				<p class="design">@2015 Ukraine Pedorets Artem</p>
			</div>
		</footer>
	</div>
</body>
</html>