<?php 
    include dirname(__FILE__) . '/options.php';
    include dirname(__FILE__) . '/db.php';
?>

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Colibri | Contact us</title>
<!-- Bootstrap -->
<link href="css/bootstrap.css" rel='stylesheet' type='text/css'/>
<!-- Font Awesome  -->
<link href="css/font-awesome.min.css" rel="stylesheet">
<!-- Custom CSS -->
<link href="css/style.css" rel="stylesheet" type="text/css" media="all"/>
<script src="js/jquery.min.js"></script>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
      <a class="navbar-brand" href="index.html"><i class="fa fa-sun-o"></i> Colibri</a> </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">Home</a></li>
        <li class="active"><a href="invites.phtml">Invites</a></li>
        <li><a href="users.phtml">Users</a></li>
      </ul>
    </div>
  </div>
</nav>
<div id="section_header">
  <div class="container">
    <h2><span>Invites</span> info</h2>
  </div>
</div>
<div class="contact">
  <div class="container">
    <div class="col-md-2"></div> 
    <div class="col-md-8" >
        <?php $result = (get_invites($db)); ?>
            <?php if(empty($result)): ?>
                <div class="alert-danger error-content">
                    <p>NO DATA</p>
                </div>
        <?php else: ?>
        <table class="table table-hover tbl-invites">
            <thead>
                <tr>
                    <th>Invite</th>
                    <th>Status</th>
                    <th>Registration date</th>
                </tr>
            </thead>
            <tbody>                        
                <?php foreach ($result as $item): ?>
                <tr>
                    <td><?=$item['invite']; ?></td>
                    <td><?=$item['status']; ?></td>
                    <td><?=$item['date_status']; ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php endif; ?>              
    </div>
  </div>
</div>
<!-- Footer -->
<div id="footerwrap">
  <div class="container">
    <div class="row">
      <div class="col-md-8"> <span class="copyright">Copyright &copy; 2015 Your Website Name. Design by <a href="http://www.templategarden.com" rel="nofollow">TemplateGarden</a></span> </div>
      <div class="col-md-4">
        <ul class="list-inline social-buttons">
          <li><a href="#"><i class="fa fa-twitter"></i></a> </li>
          <li><a href="#"><i class="fa fa-facebook"></i></a> </li>
          <li><a href="#"><i class="fa fa-google-plus"></i></a> </li>
          <li><a href="#"><i class="fa fa-linkedin"></i></a> </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!-- Bootstrap core JavaScript --> 
<script type="text/javascript" src="js/bootstrap.min.js"></script>
</body>
</html>