<div class="add_news">
<form action="" method="post">
	
	<table class="add_edit_page" cellspacing="0" cellpadding="0">
	  <tr>
		<td class="add-edit-txt">Название новости:</td>
		<td><input class="head-text" type="text" name="title" value="<??>" /></td>
	  </tr>
	  <tr>
		<td>Ключевые слова:</td>
		<td><input class="head-text" type="text" name="keywords" value="<??>" /></td>
	  </tr>
      <tr>
		<td>Описание:</td>
		<td><input class="head-text" type="text" name="description" value="<??>" /></td>
	  </tr>
      <tr>
		<td>Дата новости:</td>
		<td><input class="date-text" type="text" name="date" value="<??>" /></td>
	  </tr>
      <tr>
		<td>Анонс новости:</td>
		<td></td>
	  </tr>
	  <tr>
		<td colspan="2">
			<textarea id="editor1" class="full-text" name="anons"><??></textarea>
<script type="text/javascript">
	//CKEDITOR.replace( 'editor1' );
</script>
		</td>
	  </tr>
	   <tr>
		<td>Текст новости:</td>
		<td></td>
	  </tr>
	  <tr>
		<td colspan="2">
			<textarea id="editor2" class="full-text" name="text"><??></textarea>
<script type="text/javascript">
	//CKEDITOR.replace( 'editor2' );
</script>
		</td>
	  </tr>
	</table>
    <input type="image" src="../../Lib/admin/images/save_btn.jpg" id="addNews"/> 

</form>
</div>

	</div> <!-- .content -->
	</div> <!-- .content-main -->
</div> <!-- .karkas -->
</body>
</html>