<?php $addUser   = $view->getParam('addUser'); ?>

<?=$addUser; ?>

<div class="content">
	
<h2>Добавление пользователя</h2>

<form action="/admin/addUserFunc" method="post" id="idRole">
	
<table class="add_edit_page" cellspacing="0" cellpadding="0">
    <tr>
        <td class="add-edit-txt">*Имя пользователя:</td>
        <td><input class="head-text" type="text" name="firstName" value="" /></td>
    </tr>
    <tr>
        <td class="add-edit-txt">*Логин пользователя:</td>
        <td><input class="head-text" type="text" name="login" value="" /></td>
    </tr>
    <tr>
        <td class="add-edit-txt">*Пароль пользователя:</td>
        <td><input class="head-text" type="text" name="password" value="" /></td>
    </tr>
    <tr>
        <td class="add-edit-txt">*Email пользователя:</td>
        <td><input class="head-text" type="text" name="email" value="" /></td>
    </tr>
    <tr>
        <td class="add-edit-txt">Роль пользователя:</td>
        <td>
        
            <select name="role_id"  id="idRole">
                <option value="1">Admin</option>
                <option value="3">AdvancedUser</option>
                <option value="4">SuperUser</option>
                <option value="5">SimpleUser</option>    
            </select>

        </td>
    </tr>
</table>
	
	<input type="image" src="" /> 

</form>


	</div> <!-- .content -->
	</div> <!-- .content-main -->
</div> <!-- .karkas -->
</body>
</html>