
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/../../lib/admin/style.css" />
<link rel="stylesheet" href="/../../lib/fancybox/source/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
<script type="text/javascript" src="/Lib/js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="/lib/admin/js/admin.js"></script>
<script type="text/javascript" src="/lib/fancybox/lib/jquery.mousewheel-3.0.6.pack.js"></script>
<script type="text/javascript" src="/lib/fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>

<title>Список страниц</title>
</head>

<body>
<div class="karkas">
	<div class="head">
		<a href="#"><img src="/../../Lib/admin/images/logoAdm.jpg"/></a>
		<p><a href="#">Admin</a> | <a href="/" id="logout"><?=$userEmail = ''; ?><strong>Выйти</strong></a></p>
                
	</div> <!-- .head -->