<?php if($userRoleId != Model_User::ROLE_ADMIN_ID): ?>
        <h2>Ненадо так делать</h2>
    <?php exit(); endif;?>

<?php

function str_size($str,$length)
{ $str = iconv("UTF-8","windows-1251", $str); $str = substr($str, 0, $length); $str = iconv("windows-1251", "UTF-8", $str); $str .= ""; return $str;
}

include 'header.phtml';

// LEFTBAR
include 'leftbar.phtml';

// CONTENT
if($actionName !== 'index') { include $actionName.'.phtml'; }
else { ?>
        
<?php $currentPage  = $view->getParam('currentPage'); ?>
<?php $limit        = $view->getParam('limit'); ?>
<?php $orderType    = $view->getParam('orderType'); ?>
<?php $orderBy      = $view->getParam('orderBy'); ?>
<?php $products     = $view->getParam('products'); ?>

<div class="content">
    <h2>Каталог</h2>			
<div class="tables">
<?php if(!empty($products)) :?>
    <table class="table1">
    <thead>
        <tr>
            <th scope="col" abbr="Starter">
                <?php if($orderType == 'asc') : ?>
                <a href='/admin/index/page/<?php echo $currentPage;?>/limit/<?php echo $limit;?>/orderby/id/ordertype/desc'>Id<?php if($orderBy == 'id') :?>&darr;<?php endif; ?></a>
                <?php else : ?>
                    <a href='/admin/index/page/<?php echo $currentPage;?>/limit/<?php echo $limit;?>/orderby/id/ordertype/asc'>Id<?php if($orderBy == 'id') :?>&uarr;<?php endif; ?></a>
                <?php endif; ?>
            </th>
            <th scope="col" abbr="Medium">
                <?php if($orderType == 'asc') : ?>
                <a href='/admin/index/page/<?php echo $currentPage;?>/limit/<?php echo $limit;?>/orderby/name/ordertype/desc'>Name<?php if($orderBy == 'name') :?>&darr;<?php endif; ?></a>
                <?php else : ?>
                    <a href='/admin/index/page/<?php echo $currentPage;?>/limit/<?php echo $limit;?>/orderby/name/ordertype/asc'>Name<?php if($orderBy == 'name') :?>&uarr;<?php endif; ?></a>
                <?php endif; ?>
            </th>
            <th scope="col" abbr="Business">Description</th>
            <th scope="col" abbr="Business">Picture</th>
            <th scope="col" abbr="Deluxe">
                <?php if($orderType == 'asc') : ?>
                <a href='/admin/index/page/<?php echo $currentPage;?>/limit/<?php echo $limit;?>/orderby/price/ordertype/desc'>Price<?php if($orderBy == 'price') :?>&darr;<?php endif; ?></a>
                <?php else : ?>
                    <a href='/admin/index/page/<?php echo $currentPage;?>/limit/<?php echo $limit;?>/orderby/price/ordertype/asc'>Price<?php if($orderBy == 'price') :?>&uarr;<?php endif; ?></a>
                <?php endif; ?>
            </th>
            <th scope="col" abbr="">
                <?php if($orderType == 'asc') : ?>
                <a href='/admin/index/page/<?php echo $currentPage;?>/limit/<?php echo $limit;?>/orderby/total/ordertype/desc'>Total<?php if($orderBy == 'total') :?>&darr;<?php endif; ?></a>
                <?php else : ?>
                    <a href='/admin/index/page/<?php echo $currentPage;?>/limit/<?php echo $limit;?>/orderby/total/ordertype/asc'>Total<?php if($orderBy == 'total') :?>&uarr;<?php endif; ?></a>
                <?php endif; ?>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody class="base">
    <?php foreach($products as $product) : ?>
        <tr class="base-tr deleteProd updateProd" id="<?php echo $product->id;?>" >
                <td><?php echo $product->id;?></td>
                <td><?php echo $product->name;?></td>
                <td><?php echo str_size($product->description,50);?></td>
                <td><?php echo $product->img;?></td>
                <td><?php echo $product->price;?></td>
                <td><?php echo $product->total;?></td>
             <td scope="row">
                 <a class="update-prod fancybox scope" id ="<?php echo $product->id;?>" href="#data"><img src="/Lib/admin/images/adm-modify.png"></a>
                 <a class ="scope" href ="/admin/deleteProd/id/<?php echo $product->id; ?>" id="deleteProd"><img src="/Lib/admin/images/adm-delete.png"></a>
            </td>  
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>
</div> 
    
<!-- FlaxyBox -->            

<div style="display: none">
    <div id="data">
        <p>Id&nbsp;-&nbsp; <span id="id"><span></p>
        <form action="/admin/updateProd" method="post">
           
            <label for="name">Name</label>
            <input id= "name" type="text" value=""><br>
            <label for="price">Price</label>
            <input id= "price" type="text"><br>
            <label for="total">Total</label>
            <input id= "total" type="text"><br>
            
            <label for="description">Description</label>
            <textarea name="description"></textarea><br>
            <input type="submit" value="Сохранить" id="saveChange">
        </form>
    </div>

</div>
                        
</div> <!-- .content -->

</div> <!-- .content-main -->
 <?php } ?>         
</div> <!-- .karkas -->


</body>
</html>
