<?php $order     = $view->getParam('order'); ?>
<?php $summaOrder   = $view->getParam('summaOrder'); ?>

<div class="content">
	<h2>Заказ № <?=$summaOrder[0]->order_id;?></h2>
<p>

<a class="edit" href="/admin/confirmOrder">Подтвердить заказ</a> |

<a class="del" href="/admin/deleteOrder">Удалить заказ</a>
</p>

<br />
<?php if(!empty($order)) :?>
<table class="tabl" cellspacing="1">
    <tr>
        <th class="number">№</th>
        <th class="str_name" style="width:280px;">Название товара</th>
        <th class="str_sort">Цена</th>
        <th class="str_action">Количество</th>
    </tr>

    <?php foreach( $order  as $item) : ?>
    <tr>
        <td><?=$item->prodId; ?></td>
        
        <td class="name_page"><?=$item->prodName; ?></td>
       
        <td><?=$item->prodPrice?> р.</td>
        
        <td><?=$item->prodQuant; ?></td>
    </tr>
     <?php endforeach; ?>

</table>

<?php  elseif($view->getParam('error')) : ?>
    <div style="color:red;"><h1><?php echo $view->getParam('error')?></h1></div>
<?php endif; ?> 

    
<h2>Общая цена заказа: <span style="color:#e35a0f;"><?=$summaOrder[0]->summa;?> р.</span></h2>
<h2>Дата заказа: <span style="color:#e35a0f;"></span></h2>
<h2>Способ доставки: <span style="color:#e35a0f;"></span></h2>

<h2>Данные покупателя:</h2>
            
<table class="tabl" cellspacing="1">
    <tr>
        <th class="number" style="width:140px;">ФИО</th>
        <th class="str_name" style="width:200px;">Адрес</th>
        <th class="str_sort">Для связи</th>
        <th class="str_action">Примечание</th>
    </tr>
    <tr>
        <td></td>
        <td class="name_page"></td>
        <td>Email: <br />Телефон: </td>
        <td style="text-align:left;"></td>
    </tr>
</table>

<p>

<a class="edit" href="/admin/confirmOrder">Подтвердить заказ</a> |

<a class="del" href="/admin/deleteOrder">Удалить заказ</a>
</p>


<div class="error">Заказа с таким номером нет</div>

	</div> <!-- .content -->
	</div> <!-- .content-main -->
</div> <!-- .karkas -->
</body>
</html>