
	<div class="content-main">
		<div class="leftBar">
			<ul class="nav-left">
				<li><a href="#" class="nav-activ">Основные страницы</a></li>
				<li><a href="/admin/index">Главная</a></li>
				<li><a href="/admin/news">Новости</a></li>
                                <li><a href="/admin/orders">Заказы</a></li>
				<li><a href="/admin/users">Пользователи</a></li>
                                <li><a href="/admin/about">Контактная информация</a></li>
                                <li><a href="/admin/portfolio">О магазине</a></li>
                                
			</ul>
		</div> <!-- .leftBar -->