<?php $currentPage  = $view->getParam('currentPage'); ?>
<?php $limit        = $view->getParam('limit'); ?>
<?php $orderType    = $view->getParam('orderType'); ?>
<?php $orderBy      = $view->getParam('orderBy'); ?>
<?php $news    = $view->getParam('news'); ?>

<div class="content">
	<h2>Список новостей</h2>
	<a href="/admin/addNews"><img class="add_some" src="../../Lib/admin/images/add_news.jpg" alt="добавить страницу" /></a>
	<table class="tab2" cellspacing="1">
        <thead>   
	  <tr>
		<th class="number">№</th>
		<th class="str_name">Название страницы</th>
		<th class="str_sort">Дата</th>
		<th class="str_action">Действие</th>
	  </tr>
        </thead> 
        <tbody>
<?php if(!empty($news)) :?>
<?php foreach($news as $news) : ?>
<tr class="deleteNews">
    <td><?=$news->id; ?></td>
    <td class="name_page"><?=$news->title; ?></td>
    <td><?=$news->date; ?></td>
    <td><a href="/admin/editNews/id/<?=$news->id; ?> " class="edit" id="editNews">изменить</a>&nbsp; | &nbsp;<a href="/admin/deleteNews/id/<?=$news->id; ?>" class="del" id="deleteNews">удалить</a></td>
</tr>

<?php endforeach; ?>
<?php  elseif($view->getParam('error')) : ?>
    <div style="color:red;"><h1><?php echo $view->getParam('error')?></h1></div>
<?php endif; ?>    
 </tbody>
	</table>
	<a href="/admin/addNews"><img class="add_some" src="../../Lib/admin/images/add_news.jpg" alt="добавить страницу" /></a>
                
	</div> <!-- .content -->
	</div> <!-- .content-main -->
</div> <!-- .karkas -->
</body>
</html>